apiVersion: cloudscale.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: provider-jet-cloudscale-secret
      namespace: crossplane-system
      key: credentials
