= Getting Started

This page describes how to get a Cloudscale user and consume it in an application.

Target Audience::
Service Consumer (Developer)

== Prerequisites

* `kubectl`
* K8s cluster with Crossplane and provider-jet-cloudscale installed and configured
* `KUBECONFIG` environment variable pointing to a kubeconfig file for said cluster (or equivalent configuration)

== Steps

. If necessary create a new namespace `my-project`.
+
[source,bash]
----
kubectl create namespace my-project
----

. Create the following `User` resource in a file:
+
.demouser.yaml
[source,yaml]
----
apiVersion: objects.cloudscale.jet.crossplane.io/v1alpha1
kind: User
metadata:
  name: demouser <1>
  namespace: my-project <2>
spec:
  forProvider:
    displayName: DemoUser <3>
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: demouser-secret <4>
    namespace: my-project <5>
----
<1> Name of the Kubernetes resource
<2> Create the resource in your project namespace
<3> Name of the Cloudscale user to be created
<4> Name of the secret to put the user credentials into. Created by Crossplane.
<5> Namespace of the secret. Normally equal to the project namespace.

. Apply the resource:
+
[source,bash]
----
kubectl apply -f demouser.yaml
----

. Get the credentials from the secret generated by Crossplane. It may take a few seconds to appear.
+
[source,bash]
----
kubectl get secret demouser-secret -n my-project -oyaml
----
+
[source,yaml]
----
apiVersion: v1
data:
  access_key_0: [...]
  secret_key_0: [...]
kind: Secret
metadata:
  [...]
----
Cloudscale supports more than one pair of keys per user, hence the index.

. Configure the application to use the secret created by Crossplane
