apiVersion: objects.cloudscale.jet.crossplane.io/v1alpha1
kind: User
metadata:
  name: demouser
spec:
  forProvider:
    displayName: DemoUser
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: sample-access-key-secret
    namespace: crossplane-system
