apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-jet-cloudscale
spec:
  controller:
    image: DOCKER_REGISTRY/vshn/provider-jet-cloudscale/provider-jet-cloudscale-controller:VERSION
